spring.application.name=bankapp-java-api-backend


# ---- Datasource MongoDBCloudAtlas--
spring.mongodb.uri=mongodb+srv://genesisescobarcs_db_user:cWlcpu9Tb0a6BBPw@bankapp-cluster.q84ibx6.mongodb.net/bankapp?retryWrites=true&w=majority

